[aliases]
s = ["log", "--limit", "10"]
l = ["log"]
ab = ["bookmark", "advance"]
mm = ["bookmark", "set", "main"]
sb = ["bookmark", "set"]
pb = ["git", "push"]
rb = ["rebase", "-d", "main@origin"]

[user]
name = "Anthony Templeton"
email = "twantempleton11@gmail.com"

[remotes.origin]
auto-track-bookmarks = "glob:*"
