---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    # username: "{{ lookup('env', 'SUDO_USER') | default('vscode') }}"
    username: >-
      {{ (lookup('env', 'SUDO_USER') | default('')) 
         or (lookup('env', 'USER') | default('')) 
         or 'vscode' }}
    home_dir: "/home/{{ username }}"
    go_version: "1.24.2"

  tasks:
    # -- SYSTEM SETUP (root) --

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system packages
      apt:
        name:
          - zsh
          - python3
          - python3-venv
          - pkg-config
          - fd-find
          - wget
          - curl
          - git
          - lsb-release
          - software-properties-common
          - gnupg
          - valgrind
          - cloc
          - libsdl2-dev
        state: present

    - name: Download Go
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go
      unarchive:
        src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: Create symlink for Go
      file:
        src: /usr/local/go/bin/go
        dest: /usr/local/bin/go
        state: link
        force: yes

    - name: Remove Go tarball
      file:
        path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        state: absent


    - name: Set zsh as default shell
      user:
        name: "{{ username }}"
        shell: /bin/zsh

    # -- USER SETUP (no root) --

    - name: Install Starship prompt
      become: no
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
      args:
        creates: "{{ home_dir }}/.cargo/bin/starship"
        executable: /bin/bash

    - name: Install Zoxide
      become: no
      shell: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
      args:
        creates: "{{ home_dir }}/.local/bin/zoxide"
        executable: /bin/bash

    - name: Create local bin directory
      file:
        path: "{{ home_dir }}/.local/bin"
        state: directory
        mode: '0755'
      become: no

    - name: Install hugo
      become: no
      shell: go install github.com/gohugoio/hugo@latest
      args:
        creates: "{{ home_dir }}/go/bin/hugo"
        executable: /bin/bash

    - name: Install lazygit
      become: no
      shell: go install github.com/jesseduffield/lazygit@latest
      args:
        creates: "{{ home_dir }}/go/bin/lazygit"
        executable: /bin/bash


    - name: Download zigup tarball
      get_url:
        url: https://github.com/marler8997/zigup/releases/latest/download/zigup-x86_64-linux.tar.gz
        dest: /tmp/zigup.tar.gz
        mode: '0644'
      register: zigup_download
      become: no

    - name: Extract zigup binary
      unarchive:
        src: /tmp/zigup.tar.gz
        dest: "{{ home_dir }}/.local/bin/"
        remote_src: yes
        mode: '0755'
        creates: "{{ home_dir }}/.local/bin/zigup"
      become: no

    - name: Clean up zigup tarball
      file:
        path: /tmp/zigup.tar.gz
        state: absent

    - name: Install Zig master using zigup
      shell: |
        export PATH="{{ home_dir }}/.local/bin/:$PATH"
        {{ home_dir }}/.local/bin/zigup master --path-link {{ home_dir }}/.local/bin/zig
      register: zig_install
      changed_when: "'already installed' not in zig_install.stderr"
      become: no

    - name: Verify Zig installation
      shell: |
        export PATH="{{ home_dir }}/.local/bin:{{ home_dir }}/.local/zig:$PATH"
        zig version
      register: zig_version
      changed_when: false
      become: no

    - name: Display Zig version
      debug:
        var: zig_version.stdout

    - name: Download c3 tarball
      get_url:
        url: https://github.com/c3lang/c3c/releases/latest/download/c3-linux.tar.gz
        dest: /tmp/c3-linux.tar.gz
        mode: '0644'
      register: c3c_download
      become: no

    - name: Extract c3 binary
      unarchive:
        src: /tmp/c3-linux.tar.gz
        dest: "{{ home_dir }}/.local/bin/"
        remote_src: yes
        mode: '0755'
        creates: "{{ home_dir }}/.local/bin/c3/c3c"
      become: no

    - name: Clean up c3 tarball
      file:
        path: /tmp/c3-linux.tar.gz
        state: absent

    - name: Verify c3 installation
      shell: |
        export PATH="{{ home_dir }}/.local/bin/c3/:$PATH"
        c3c --version
      register: c3c_version
      changed_when: false
      become: no

    - name: Display c3 version
      debug:
        var: c3c_version.stdout

    - name: Download OpenTofu install script
      get_url:
        url: https://get.opentofu.org/install-opentofu.sh
        dest: /tmp/install-opentofu.sh
        mode: '0755'

    - name: Install OpenTofu
      shell: /tmp/install-opentofu.sh --install-method deb
      args:
        creates: /usr/local/bin/tofu

    - name: Verify OpenTofu installation
      command: tofu version
      register: tofu_version

    - name: Display OpenTofu version
      debug:
        msg: "OpenTofu installed: {{ tofu_version.stdout }}"

    - name: Clean up install script
      file:
        path: /tmp/install-opentofu.sh
        state: absent

    - name: Install rustup
      become: no
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ home_dir }}/.cargo/bin/rustup"
        executable: /bin/bash

    - name: Install bob (Neovim version manager)
      become: no
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install bob-nvim
      args:
        creates: "{{ home_dir }}/.cargo/bin/bob"
        executable: /bin/bash

    - name: Install just (makefile alternative)
      become: no
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install just
      args:
        creates: "{{ home_dir }}/.cargo/bin/just"
        executable: /bin/bash

    - name: Install Neovim nightly using bob
      become: no
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        bob use nightly || echo "failed to set nightly, but continuing"
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Install NVM
      shell: |
        export NVM_DIR="{{ home_dir }}/.nvm"
        mkdir -p "$NVM_DIR"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
      args:
        creates: "{{ home_dir }}/.nvm/nvm.sh"
        executable: /bin/bash
      become: no
      environment:
        HOME: "{{ home_dir }}"  # Correcting the HOME variable to the user's home dir

    - name: Install Node.js using NVM
      shell: |
        export NVM_DIR="{{ home_dir }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
        nvm install 22
        nvm use 22
      args:
        executable: /bin/bash
      become: no
      environment:
        HOME: "{{ home_dir }}"  # Correcting the HOME variable to the user's home dir

    - name: Install uv package manager
      become: no
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ home_dir }}/.local/bin/uv"
        executable: /bin/bash

    - name: Install fzf
      become: no
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ home_dir }}/.fzf"
        depth: 1

    - name: Run fzf installer
      become: no
      shell: "{{ home_dir }}/.fzf/install --all"
      args:
        creates: "{{ home_dir }}/.fzf/bin/fzf"
        executable: /bin/bash

    - name: Download LLVM installation script
      get_url:
        url: https://apt.llvm.org/llvm.sh
        dest: /tmp/llvm.sh
        mode: '0755'

    - name: Execute LLVM installation script
      command: /tmp/llvm.sh 19
      become: yes
      args:
        creates: /usr/bin/clang-19

    - name: Verify Clang 19 installation
      command: clang-19 --version
      register: clang_version
      changed_when: false

    - name: Create symlink for current clang version
      file:
        src: "/usr/bin/clang-19"
        dest: "/usr/bin/clang"
        state: link
        force: yes


    - name: Display Clang version
      debug:
        var: clang_version.stdout

    - name: Clean up installation script
      file:
        path: /tmp/llvm.sh
        state: absent

