---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    username: "{{ ansible_user_id }}"  # Use ansible_user_id directly
    home_dir: "/home/{{ username }}"
    go_version: "1.24.2"

  tasks:
    # -- SYSTEM SETUP (root) --

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system packages
      apt:
        name:
          - zsh
          - python3
          - python3-venv
          - pkg-config
          - fd-find
          - wget
          - curl
          - git
        state: present

    - name: Download Go
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go
      unarchive:
        src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: Create symlink for Go
      file:
        src: /usr/local/go/bin/go
        dest: /usr/local/bin/go
        state: link
        force: yes

    - name: Remove Go tarball
      file:
        path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        state: absent

    - name: Set zsh as default shell
      user:
        name: "{{ username }}"
        shell: /bin/zsh

    # -- USER SETUP (no root) --

    - name: Install Starship prompt
      become: no
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
      args:
        creates: "{{ home_dir }}/.cargo/bin/starship"
        executable: /bin/bash

    - name: Install Zoxide
      become: no
      shell: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
      args:
        creates: "{{ home_dir }}/.local/bin/zoxide"
        executable: /bin/bash

    - name: Install rustup
      become: no
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ home_dir }}/.cargo/bin/rustup"
        executable: /bin/bash

    - name: Install bob (Neovim version manager)
      become: no
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install --git https://github.com/MordechaiHadad/bob.git
      args:
        creates: "{{ home_dir }}/.cargo/bin/bob"
        executable: /bin/bash

    - name: Install Neovim nightly using bob
      become: no
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        bob use nightly || echo "failed to set nightly, but continuing"
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Install NVM
      shell: |
        export NVM_DIR="{{ home_dir }}/.nvm"
        mkdir -p "$NVM_DIR"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
      args:
        creates: "{{ home_dir }}/.nvm/nvm.sh"
        executable: /bin/bash
      become: no
      environment:
        HOME: "{{ home_dir }}"  # Correcting the HOME variable to the user's home dir

    - name: Install Node.js using NVM
      shell: |
        export NVM_DIR="{{ home_dir }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
        nvm install 22
        nvm use 22
      args:
        executable: /bin/bash
      become: no
      environment:
        HOME: "{{ home_dir }}"  # Correcting the HOME variable to the user's home dir

    - name: Install uv package manager
      become: no
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ home_dir }}/.local/bin/uv"
        executable: /bin/bash

    - name: Install fzf
      become: no
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ home_dir }}/.fzf"
        depth: 1

    - name: Run fzf installer
      become: no
      shell: "{{ home_dir }}/.fzf/install --all"
      args:
        creates: "{{ home_dir }}/.fzf/bin/fzf"
        executable: /bin/bash

