#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
#
# Add this to your River init file
riverctl map normal Super+Shift L spawn "gtklock"

#riverctl map normal Super Return spawn kitty
riverctl map normal Super Return spawn ghostty
riverctl map normal Super o spawn zen-browser
riverctl map normal Super d spawn fuzzel
riverctl map normal Super+Shift C spawn "/home/templeton/.config/river/init"


# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl focus-follows-cursor normal

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen


# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn "/home/templeton/.config/sway/scripts/sound.sh --inc"
    riverctl map $mode None XF86AudioLowerVolume  spawn "/home/templeton/.config/sway/scripts/sound.sh --dec"
    riverctl map $mode None XF86AudioMute  spawn "/home/templeton/.config/sway/scripts/sound.sh --mute"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    #riverctl map $mode None XF86AudioPlayPause spawn "/home/mukul/.config/river/scripts/MediaCtrl.zsh --pause"
    #riverctl map $mode None XF86AudioPause spawn "/home/mukul/.config/river/scripts/MediaCtrl.zsh --pause"
    #riverctl map $mode None XF86AudioPlay  spawn "/home/mukul/.config/river/scripts/MediaCtrl.zsh --pause"
    #riverctl map $mode None XF86AudioPrev  spawn "/home/mukul/.config/river/scripts/MediaCtrl.zsh --prv"
    #riverctl map $mode None XF86AudioNext  spawn "/home/mukul/.config/river/scripts/MediaCtrl.zsh --nxt"

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn "/home/templeton/.config/sway/scripts/brightness.sh --inc"
    riverctl map $mode None XF86MonBrightnessDown spawn "/home/templeton/.config/sway/scripts/brightness.sh --dec"

done

riverctl declare-mode launcher
riverctl map normal   Super z      enter-mode launcher
riverctl map launcher None f spawn firefox
#riverctl map normal Super N spawn "WEBKIT_DISABLE_COMPOSITING_MODE=1 nyxt"
riverctl map launcher None t spawn thunar
riverctl map launcher None Escape enter-mode normal

# Set background and border color
riverctl border-width 2
riverctl border-color-unfocused 0x353535
riverctl border-color-focused 0xffffff

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
#riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add ssd
# riverctl xcursor-theme oreo-blue-cursors

#riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id float float
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -app-id 'GParted' float
riverctl rule-add -app-id 'nwg-look' float
riverctl rule-add -app-id 'blueman-manager' float
riverctl rule-add -app-id 'firefox' -title 'Picture-in-Picture' float
riverctl rule-add -title 'gtk*' float
riverctl rule-add -app-id 'xdg-desktop-portal-gtk' float


#enable tap to click

riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap enabled
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad accel-profile none
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad click_method clickfinger
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad natural-scroll enabled
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad middle-emulation enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
#riverctl set-repeat 50 300

riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

# force lock



processes=("wlsunset" "swaybg" "polkit-mate-aut" "nm-applet" "blueman-applet" "waybar" "mako")

for process in "${processes[@]}"; do
    if pgrep -f "$process"; then
        pkill -f "$process" > /dev/null; sleep 0.25
    fi
done

xset b off &
nm-applet &
wl-paste --watch cliphist store &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
swaybg -i /home/templeton/Pictures/wp_dbz.png -m fill &
waybar &
mako &
# blueman-applet &
wlsunset -S 06:30 -s 23:00 -t 5500 -T 6500 &

riverctl default-layout rivertile
rivertile -view-padding 3 -outer-padding 3 -main-ratio 0.5 &


# Start swayidle
swayidle -w \
    timeout 300 'gtklock' \
    timeout 600 'riverctl spawn "wlr-randr --output \* --off"' \
    resume 'riverctl spawn "wlr-randr --output \* --on"' \
    before-sleep 'gtklock' &

riverctl spawn "swaddle"

# way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

# Environment Variables
export MOZ_ENABLE_WAYLAND=1
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=wlroots
#QT_QPA_PLATFORMTHEME=qt6ct

